backend/DjangoProject/DjangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('store/', include('Store.urls', namespace='Store')),
    path('cart/', include('ShoppingCart.urls', namespace='ShoppingCart')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/DjangoProject/ShoppingCart/urls.py
from django.urls import path
from . import views


app_name = 'ShoppingCart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('OrderCreating/', views.order_create, name='order_create')
]

backend/DjangoProject/Store/urls.py
from django.urls import path, re_path
from . import views
from django.views.generic import TemplateView


app_name = 'Store'
urlpatterns = [
    path('', TemplateView.as_view(template_name='Basic/MainPage.html'), name='MainPage'),
    path('products/', views.ProductList, name='ProductList'),
    path('products/categories/<slug:category_slug>/',
         views.ProductList, name='products_with_category_slug'),
    path('detail/<int:product_id>/<slug:product_slug>/',
         views.ProductDetail, name='ProductDetail')
]

backend/DjangoProject/Store/models.py
from django.db import models
from django.urls import reverse
from mptt.models import MPTTModel, TreeForeignKey


# Create your models here.


class Publisher(models.Model):
    pass


class Category(MPTTModel, models.Model):
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    name = models.CharField(max_length=100, db_index=True, unique=True)
    slug = models.SlugField(max_length=100, db_index=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    class MPTTMeta:
        order_insertion_by = ['name']

    def get_absolute_url(self):
        return reverse('Store:products_with_category_slug', kwargs={'category_slug': self.slug})

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    description = models.TextField(max_length=4000)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='ProductImage', blank=True)
    stock = models.PositiveIntegerField()
    available = models.BooleanField()
    slug = models.SlugField(max_length=100, db_index=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    category = models.ManyToManyField(Category, related_query_name='entry')

    class Meta:
        index_together = (('id', 'slug'),)
        ordering = ['name', 'price']
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    def get_absolute_url(self):
        return reverse('Store:ProductDetail',
                       kwargs={'product_id': self.pk, 'product_slug': self.slug})

    def __str__(self):
        return self.name

backend/DjangoProject/Store/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404
from .models import Product, Category
from ShoppingCart.forms import AddProductForm
from django.views.generic import DetailView, ListView
from .handlers import pagination_handler


def ProductList(request, category_slug=None):
    """
    used pagination
    :param request: type => HttpRequest(). user request objects
    :param category_slug: type => category url-slug
    :return: render: type => HttpResponse object, template = ProductList.html, context = context_dict
            if Slug: context_dict = specific categories and related products.
    """
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    product_limit = pagination_handler(request, products, 5)
    context_dict = {'categories': categories, 'product_limit': product_limit}
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        filtered_products = products.filter(category=category)
        product_limit = pagination_handler(request, filtered_products, 5)
        context_dict.update({'product_limit': product_limit, 'category': category})
    return render(request, 'Store/ProductList.html', context=context_dict)


# class ProductDetail(DetailView):
#     template_name = 'Store/ProductDetail.html'
#     model = [Product, Category]
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         product_detail = get_object_or_404(Product, pk=kwargs['product_id'],
#                                                       slug=kwargs['product_slug'], available=True)
#         context['product_detail'] = product_detail.objects.all()
#         context['nested'] = product_detail.category.all()
#         context['add_product_to_cart'] = AddProductForm()
#         return context


def ProductDetail(request, product_id, product_slug):
    """
    receipt specific product by id and product_slug, formation of nested categories.
    Obtaining a form for choosing the quantity of goods.
    :param request: type => HttpRequest(). user request objects
    :param product_id: type => int. product id
    :param product_slug: type => product url-slug
    :return: render: type => HttpResponse object, template = ProductDetail.html, context = context_dict
    """
    product_detail = get_object_or_404(Product, pk=product_id, slug=product_slug, available=True)
    nested_category = product_detail.category.all()
    add_product_to_cart = AddProductForm()
    context_dict = {'product_detail': product_detail,
                    'nested': nested_category,
                    'add_product_to_cart': add_product_to_cart}
    return render(request, 'Store/ProductDetail.html', context=context_dict)

backend/DjangoProject/templates/Store/ProductDetail.html
{% extends 'Basic/MainPage.html' %}
{% load static %}
{% load mptt_tags %}

{% block title %}
    {% if product_detail %}
        {{ product_detail.name }}
    {% else %}
        Products
    {% endif %}
{% endblock title %}

{% block content %}
        {% if product_detail %}
            <h2>{{ product_detail.name }}</h2>
        {% else %}
            <h2>Detail page</h2>
        {% endif %}

            <p>Nested category branch:

                {% for nested_branch_category in nested.get_ancestors %}
                        <a href="{{ nested_branch_category.get_absolute_url }}">{{ nested_branch_category }}</a> /
                {% endfor %}</p>

        <div id="detail">
            {% if product_detail.image %}
                <img src="{{ product_detail.image.url }}" alt="{{ product_detail.name }}">
            {% else %}
                <img src="{% static 'Store/img/ImageNotFound.jpg' %}" alt="{{ product_detail.name }}">
            {% endif %}
            <h3>{{ product_detail.name }} - price: <strong>{{ product_detail.price }}$</strong></h3>

            <form action="{% url 'ShoppingCart:add_to_cart' product_detail.pk %}" method="post">
                {% csrf_token %}
                {{ add_product_to_cart }}
                <input type="submit" value="Add to cart">
            </form>

            <hr>
                <h2>Description</h2>
                <p>{{ product_detail.description|linebreaks }}</p>
            <hr>

        <p>Categories associated with the product</p>
            <a href="{% url 'Store:ProductList' %}">All categories</a><br>
            {% for nested_val in nested %}
                <a href="{{ nested_val.get_absolute_url }}">{{ nested_val }}</a><br>...
            {% endfor %}

    </div>
{% endblock content %}

backend/DjangoProject/templates/Store/ProductList.html
{% extends 'Basic/MainPage.html' %}
{% load static %}
{% load mptt_tags %}

{% block title %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Products
    {% endif %}
{% endblock title %}


{% block content %}
    <div id="CategoryBar">
        <ul>
            <li {% if not category %}{% endif %}>
                <a href="{% url 'Store:ProductList' %}">ALL CATEGORIES</a>
            </li>

                {% for categories_val, struct in categories|tree_info %}
                    {% if struct.new_level %}
                        <ul><li>{% else %}</li><li>{% endif %}
                            <a href="{{ categories_val.get_absolute_url }}">{{ categories_val.name }}</a>
                    {% for level in struct.closed_level %}
                        </li></ul>
                    {% endfor %}
                {% endfor %}
        </ul>
    </div>

    <div id="subheader">
        {% with sum_items=shopping_cart_processor|length  %}
            {% if shopping_cart_processor|length > 0 %}
                <a href="{% url 'ShoppingCart:cart_detail' %}">cart detail</a>:
                <strong>{{ sum_items }} product.</strong> {{ sum_items|pluralize }}
                total price <strong>{{ shopping_cart_processor.full_price }}$</strong>
            {% else %}
                <div class="cart">
                    <a href="{% url 'ShoppingCart:cart_detail' %}">Your cart is empty</a>
                </div>
            {% endif %}
        {% endwith %}
    </div>

    <hr>
    <div id="ProductList">
        <h2>
            {% if category %}{{ category.name }}{% else %}Products{% endif %}
        </h2>

        {# product_limit - pagination limit per page #}
        {% for product in product_limit %}
            <a href="{{ product.get_absolute_url }}">
            {% if product.image %}
                <img src="{{ product.image.url }}" height="400" width="400" alt="{{ product.name }}">
            {% else %}
                <img src="{% static 'Store/img/ImageNotFound.jpg' %}" height="300" width="300">
            {% endif %}
            </a>
            <br>
            <h2><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h2>
            <p>Price: <strong>{{ product.price }}$</strong></p>
        {% endfor %}
    </div>

    {# module pagination connect   #}
    {% include 'includes/pagination.html' %}
{% endblock content %}