backend/DjangoProject/DjangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('store/', include('Store.urls', namespace='Store')),
    path('cart/', include('ShoppingCart.urls', namespace='ShoppingCart')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/DjangoProject/ShoppingCart/urls.py
from django.urls import path
from . import views


app_name = 'ShoppingCart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('OrderCreating/', views.order_create, name='order_create')
]

backend/DjangoProject/Store/urls.py
from django.urls import path, re_path
from . import views
from django.views.generic import TemplateView


app_name = 'Store'
urlpatterns = [
    path('', TemplateView.as_view(template_name='Basic/MainPage.html'), name='MainPage'),
    path('products/', views.ProductList, name='ProductList'),
    path('products/categories/<slug:category_slug>/',
         views.ProductList, name='products_with_category_slug'),
    path('detail/<int:product_id>/<slug:product_slug>/',
         views.ProductDetail, name='ProductDetail')
]

backend/DjangoProject/ShoppingCart/models.py
from django.db import models
from Store.models import Product
from phone_field import PhoneField


class Customer(models.Model):
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=70)
    email = models.EmailField()
    city = models.CharField(max_length=150)
    address = models.CharField(max_length=300)
    postal_code = models.CharField(max_length=50)
    order_created = models.DateTimeField(auto_now_add=True)
    order_updated = models.DateTimeField(auto_now=True)
    payment = models.BooleanField(default=False)

    class Meta:
        ordering = ['order_created']
        verbose_name = 'Customer'
        verbose_name_plural = 'Customers'

    def __str__(self):
        return f'{self.name} {self.surname}'

    @staticmethod
    def order_access(order_id):
        custom_order = Customer.objects.get(pk=order_id)
        days_order_acceptance = custom_order.order_created.day
        if days_order_acceptance > days_order_acceptance + 5:
            custom_order.customer_items.access = False


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE,
                                 related_name='customer', related_query_name='customer_items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product',
                                related_query_name='product_items')
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveSmallIntegerField(default=1)
    access = models.BooleanField(default=True)

    def access_validator(self):
        pass

    class Meta:
        ordering = ['quantity']
        verbose_name = 'Order'
        verbose_name_plural = 'Orders'

    def __str__(self):
        return self.product.name

backend/DjangoProject/ShoppingCart/forms.py
from django import forms
from Store.models import Product
from .models import Customer


class AddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=((x, x) for x in range(1, 11)), coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)


class OrderCreatingForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('name', 'surname', 'email', 'city', 'address', 'postal_code')
        labels = {'postal_code': 'city postal code'}
        help_texts = {'postal_code': 'Enter the postal code of your city', 'address': 'Enter your address',
                      'city': 'Enter your city'}

backend/DjangoProject/ShoppingCart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.views.decorators.csrf import csrf_protect
from .forms import AddProductForm, OrderCreatingForm
from .ShoppingCart import Cart
from Store.models import Product
from .models import Order
from django.views.generic import View


# class add_to_cart(View):
#
#     def post(self, request, product_id):
#         requested_cart = Cart(request)
#         products = get_object_or_404(Product, pk=product_id)
#         add_product_form = AddProductForm(request.POST)
#         if add_product_form.is_valid():
#             form_cleaned_data = add_product_form.cleaned_data
#             requested_cart.add_product(product=products,
#                                        product_quantity=form_cleaned_data.get('quantity'),
#                                        update_quantity=form_cleaned_data.get('update'))

@require_POST
@csrf_protect
def add_to_cart(request, product_id):
    """
    pass the user request object to Cart class. Add product to shopping cart
    :param request: type => HttpRequest(). user request objects
    :param product_id: type => Model ORM. product id
    :return: type => HttpRedirect(). redirect to cart_detail() view
    """
    requested_cart = Cart(request)
    products = get_object_or_404(Product, pk=product_id)
    add_product_form = AddProductForm(request.POST)
    if add_product_form.is_valid():
        form_cleaned_data = add_product_form.cleaned_data
        requested_cart.add_product(product=products,
                                   product_quantity=form_cleaned_data.get('quantity'),
                                   update_quantity=form_cleaned_data.get('update'))
    return redirect('ShoppingCart:cart_detail')


def remove_from_cart(request, product_id):
    """
    pass the user request object to Cart class. Remove product from shopping cart
    :param request: type => HttpRequest(). user request objects
    :param product_id: type => Model ORM. product id
    :return: type => HttpRedirect(). redirect to cart_detail() view
    """
    requested_cart = Cart(request)
    product = get_object_or_404(Product, pk=product_id)
    requested_cart.remove_product(product)
    return redirect('ShoppingCart:cart_detail')


def cart_detail(request):
    """
    pass the user request object to Cart class
    :param request: type => HttpRequest(). user request objects
    :return: render: type => HttpResponse().
    """
    requested_cart = Cart(request)
    return render(request, 'ShoppingCart/Detail.html', context={'cart': requested_cart})


@csrf_protect
def order_create(request):
    requested_cart = Cart(request)
    if request.method == 'POST':
        order_creating_form = OrderCreatingForm(request.POST)
        if order_creating_form.is_valid():
            customer_save = order_creating_form.save()
            for cart_items in requested_cart:
                Order.objects.create(customer=customer_save, product=cart_items.get('product'),
                                     price=cart_items.get('price'), quantity=cart_items.get('quantity'))
            ordered_product = [value for value in customer_save.customer.all()]
            requested_cart.clear_cart_session()
            return render(request, 'ShoppingCart/OrderSuccessfully.html',
                          context={'order_successfully': customer_save, 'ordered_product': ordered_product})
    else:
        order_creating_form = OrderCreatingForm()
        return render(request, 'ShoppingCart/OrderRegistration.html',
                      context={'requested_cart': requested_cart, 'order_creating_form': order_creating_form})

backend/DjangoProject/templates/ShoppingCart/Detail.html
{% extends 'Basic/MainPage.html' %}
{% load static %}

{% block title %}Product detail{% endblock title %}

{% block content %}
    <h3>Shopping cart</h3>

            {% if cart %}
                {% for cart_item in cart %}
                    {% with product=cart_item.product %}

                        <a href="{{ product.get_absolute_url }}">
                            {% if product.image %}
                                <img src="{{ product.image.url }}" alt="{{ product.name }}">
                            {% else %}C
                                <img src="{% static 'Store/img/ImageNotFound.jpg' %}" alt="{{ product.name }}">
                            {% endif %}
                        </a>
                        <a href="{{ product.get_absolute_url }}"><h2>{{ product.name }}</h2></a>
                        <strong>Quantity: {{ cart_item.quantity }}</strong><br>
                        <strong>Price: {{ cart_item.price }}$</strong><br>
                        <strong>Total price: {{ cart_item.full_price }}$</strong><br>
                        <a href="{% url 'ShoppingCart:remove_from_cart' product.pk %}">Remove product</a><br>
                        <hr>
                    {% endwith %}
                {% endfor %}
            {% endif %}
    <p>
        <a href="{% url 'Store:ProductList' %}" class="button light">Continue shop</a> |
        {% if cart|length > 0 %}
            <a href="{% url 'ShoppingCart:order_create' %}">To order</a>
        {% endif %}
    </p>
{% endblock content %}

backend/DjangoProject/templates/ShoppingCart/OrderRegistration.html
{% extends 'Basic/MainPage.html' %}

{% block title %}Order registration{% endblock title %}

{% block content %}
    <h3>Order registration</h3>
    <hr>
    {% for cart_item in requested_cart %}
        <strong>
            quantity: {{ cart_item.quantity }}<br>
            product: <a href="{{ cart_item.product.get_absolute_url }}">{{ cart_item.product.name }}</a><br>
            price: {{ cart_item.price }}<br>
        </strong>
    {% endfor %}
    <h3>Total price: {{ requested_cart.full_price }}</h3>

    {% if order_creating_form %}
        <form action="" method="post">
            {% csrf_token %}
            {{ order_creating_form.as_p }}
            <input type="submit" value="Buy">
        </form>
        {% else %}
            <p>form not found</p>
    {% endif %}

{% endblock content %}

backend/DjangoProject/templates/ShoppingCart/OrderSuccessfully.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Order processed successfully</title>
</head>
<body>
    <h3>Hello, {{ order_successfully.name }} your order processed successfully</h3>
    <h4>Declaration</h4>
    {% for order_item in ordered_product %}
        <p><strong>Product:</strong> {{ order_item }}</p>
    {% endfor %}
    <p><strong>city:</strong> {{ order_successfully.city }}</p>
    <p><strong>address:</strong> {{ order_successfully.address }}</p>
    <p><strong>email:</strong> {{ order_successfully.email }}</p>
    <a href="{% url 'Store:MainPage' %}"><strong>Main page</strong></a>
</body>
</html>